import { ProductCardProps } from './ProductCard'

export const skincareProducts: ProductCardProps[] = [
  {
    title: 'Face Cream Jars',
    description: 'Face cream jars provide secure, airtight storage for emulsion-based formulations, protecting product integrity from first use to last application.',
    image: '/images/products/frosting-face-cream-jar.webp',
    imageAlt: 'frosting face cream jar',
    features: [
      'Airtight sealing systems prevent contamination',
      'Wide-mouth openings for easy access',
      'Common Materials: Glass, PET, PP, Acrylic',
      'Capacities: 15ml-200ml, custom',
    ],
    idealFor: 'Night creams, day creams, moisturizers, gel creams, water-gel formulations, anti-aging treatments',
    link: '/all-applications/face-cream-jars/',
  },
  {
    title: 'Face Lotion Bottles',
    description: 'Face lotion bottles protect delicate formulations while delivering controlled application for daily facial care routines.',
    image: '/images/products/Wholesale-HDPE-lotion-pump-bottles.webp',
    imageAlt: 'Wholesale HDPE lotion pump bottles',
    features: [
      'Treatment pumps deliver precise dosing (0.5ml-2ml per pump)',
      'Airless pump options prevent oxidation of active ingredients',
      'Capacities: 30ml-200ml (common sizes: 50ml, 100ml, 150ml)',
      'Ergonomic shapes for one-handed use',
    ],
    idealFor: 'Daily moisturizers, night creams, day creams with SPF, hydrating lotions, anti-aging treatments, gel-creams, tinted moisturizers',
    link: '/all-applications/lotion-bottles/',
  },
  {
    title: 'Serum Bottles',
    description: 'Serum formulations contain concentrated actives at higher percentages, making packaging choice critical for efficacy preservation.',
    image: '/images/products/glass-serum-bottles.jpg.webp',
    imageAlt: 'glass serum bottles',
    features: [
      'Dropper assemblies for precise dispensing',
      'Amber/cobalt glass blocks UV rays (99%)',
      'Capacities: 10ml-100ml (most common: 30ml, 50ml)',
      'Airless pumps available',
    ],
    idealFor: 'Hyaluronic acid serums, vitamin C treatments, retinol solutions, niacinamide formulations, peptide concentrates, facial oils',
    link: '/all-applications/serum-bottles/',
  },
  {
    title: 'Glass Vials',
    description: 'Glass vials provide hygienic packaging for concentrated skincare treatments and single-use applications. Ideal for high-potency formulations.',
    image: '/images/products/serum-vial.webp',
    imageAlt: 'serum vial',
    features: [
      'Dropper dispensers for multiple uses',
      'Break-off or twist-off closures for tamper-evident, single-use application',
      'Small capacities: 1ml-10ml (most common: 2ml, 3ml, 5ml)',
      'Individual or connected formats (multi-pack strips for treatment courses)',
    ],
    idealFor: 'Serum concentrates, vitamin C shots, retinol treatments, peptide ampoules, hyaluronic acid boosters,  professional-grade actives',
    link: '/all-applications/glass-vials/',
  },
]

export const skincareProducts2: ProductCardProps[] = [
  {
    title: 'Roll-On Bottles',
    description: 'Roll-on formats provide targeted, mess-free application across diverse personal care categories, from deodorants to therapeutic oils.',
    image: '/images/products/roll-on-bottle-for-eye-serum.webp',
    imageAlt: 'roll on bottle for eye serum',
    features: [
      'Rollerball assemblies: Glass, plastic, and metal options',
      'Leak-proof designs critical for portability',
      'Capacities: 15ml-75ml (deodorant standard: 50ml, 75ml)',
      'Glass bottles for aromatherapy and natural formulations and plastic for deodorants',
    ],
    idealFor: 'Roll-on deodorants, cooling gel roll-ons, aromatherapy pulse point oils, insect repellent, pain relief gels',
    link: '/all-applications/roll-on-bottles/',
  },
  {
    title: 'Spray Bottles',
    description: 'Spray bottles deliver even distribution through mist or stream application, ideal for facial care, body treatments, and wellness products. ',
    image: '/images/products/spray-bottle-design.webp',
    imageAlt: 'spray bottle design',
    features: [
      'Fine mist sprayers create delicate, even coverage for facial application',
      'Continuous spray options for body coverage',
      'Trigger sprayers for thicker formulations',
      'Capacities: 50ml-500ml (common sizes: 100ml, 150ml, 250ml)',
    ],
    idealFor: 'Facial mists, setting sprays, hair mists, body sprays, cooling sprays, aromatherapy sprays, linen refreshers',
    link: '/all-applications/spray-bottles/',
  },
  {
    title: 'Toner Bottles',
    description: 'Toner bottles feature dispensing systems designed for controlled application and seamless integration into daily skincare routines.',
    image: '/images/products/skincare-bottle-packaging-for-hydrating-toner.webp',
    imageAlt: 'skincare bottle packaging for hydrating toner',
    features: [
      'Disc-top caps for controlled, mess-free dispensing to cotton pad',
      'Spray mist options for hydrating facial mists and essence sprays',
      'Flip-top caps for one-handed operation',
      'Capacities: 100ml-500ml (standard retail sizes: 150ml, 200ml, 250ml)',
    ],
    idealFor: 'Hydrating toners, exfoliating toners (AHA/BHA), pH-balancing toners, essence toners, facial mists, micellar water',
    link: '/all-applications/toner-bottles/',
  },
  {
    title: 'Sunscreen Packaging',
    description: 'Sunscreen packaging accommodates chemical stability under heat, moisture resistance, and easy application during outdoor activities.',
    image: '/images/products/squeezable-cosmetic-tube-sunscreen-bottle.webp',
    imageAlt: 'squeezable cosmetic tube sunscreen bottle',
    features: [
      'High-barrier materials protect UV filters from degradation',
      'Squeeze tubes with flip-top caps for beach-friendly application',
      'Heat-resistant plastics maintain integrity in high temperatures',
      'Capacities: 50ml-250ml, custom',
    ],
    idealFor: 'Chemical sunscreens, mineral sunscreens, spray sunscreens, sunscreen sticks, tinted sunscreens',
    link: '/all-applications/sunscreen-packaging/',
  },
]

export const makeupProducts: ProductCardProps[] = [
  {
    title: 'Foundation Bottles',
    description: 'Foundation packaging has evolved from simple bottles to sophisticated dispensing systems that maintain hygiene and prevent oxidation.',
    image: '/images/products/new-design-foundation-bottles.webp',
    imageAlt: 'new design foundation bottles',
    features: [
      'Airless pump eliminates air exposure',
      'Treatment pumps for various viscosities',
      'Glass dropper options for serum foundations',
      'Capacities: 15ml-50ml (standard: 30ml)',
    ],
    idealFor: 'Liquid foundations, cushion foundation refills, serum foundations, tinted moisturizers, BB/CC creams',
    link: '/all-applications/foundation-bottles/',
  },
  {
    title: 'Lip Gloss Tubes',
    description: 'Lip gloss packaging combines precise application with visual appeal, featuring transparent components that showcase product shimmer.',
    image: '/images/products/Eco-friendly-lip-gloss-tube.webp',
    imageAlt: 'Eco-friendly lip gloss tube',
    features: [
      'Wand applicators: curved, paddle, or brush',
      'Custom shapes: Round, square, oval, uniquely branded',
      'Transparent tubes showcase shade',
      'Capacities: 3ml-15ml (standard: 5ml, 7ml)',
    ],
    idealFor: 'High-shine glosses, plumping glosses, tinted lip oils, liquid lipsticks, lip stains',
    link: '/all-applications/lip-gloss-tubes/',
  },
  {
    title: 'Mascara Tubes',
    description: 'Highly specialized packaging requiring airtight sealing to prevent formula drying and precise brush design for application effects.',
    image: '/images/products/metallic-lip-gloss-tube.webp',
    imageAlt: 'mascara tube',
    features: [
      'Brush options: curved, straight, comb',
      'Precision wipers control product amount',
      'Airtight caps prevent formula drying (critical for water-based formulas)',
      'Capacities: 5ml-15ml (standard: 8ml, 10ml)',
    ],
    idealFor: 'Volumizing mascara, lengthening mascara, curling mascara, waterproof mascara, lash primers',
    link: '/all-applications/mascara-tube/',
  },
  {
    title: 'Makeup Removers',
    description: 'Makeup remover bottles accommodate various formulation types, ensuring product integrity and user convenience.',
    image: '/images/products/airless-jar.webp',
    imageAlt: 'airless jar',
    features: [
      'Pump dispensers deliver consistent dosing for liquid removers',
      'Dropper options for concentrated oil-based and waterproof makeup removers',
      'Airless pump systems available',
      'Capacities: 50ml-250ml',
    ],
    idealFor: 'Micellar water, oil-based removers, bi-phase removers, makeup dissolving oils, eye makeup removers',
    link: '/all-applications/makeup-remover-bottles/',
  },
]

export const fragranceProducts: ProductCardProps[] = [
  {
    title: 'Perfume Bottles',
    description: 'Perfume bottles are where packaging becomes art. Every element communicates brand heritage and fragrance character.',
    image: '/images/products/perfume-bottle-new-design.webp',
    imageAlt: 'perfume bottle new design',
    features: [
      'High-quality glass: Crystal-clear, colored, frosted, or coated options',
      'Spray mechanisms: Fine mist, atomizers with varying spray patterns',
      'Custom molding capabilities for unique bottle shapes',
      'Capacities: 30ml-100ml (standard retail: 50ml, 75ml, 100ml)',
    ],
    idealFor: 'Eau de parfum, parfum concentration, eau de toilette, cologne',
    link: '/all-applications/perfume-bottles/',
  },
  {
    title: 'Portable Bottles',
    description: 'Travel-size fragrance formats prioritize portability and TSA compliance (under 100ml) while maintaining the luxury perception of full-size bottles.',
    image: '/images/products/portable-perfume-bottle.webp',
    imageAlt: 'portable perfume bottle',
    features: [
      'Spray atomizers with protective caps',
      'Rollerball applicators for purse-friendly formats',
      'Elegant miniature aesthetics mirror full-size designs',
      'Capacities: 5ml-30ml (TSA compliant)',
    ],
    idealFor: 'Travel sizes, discovery sets, sampling programs, purse atomizers',
    link: '/all-applications/portable-perfume-bottles/',
  },
  {
    title: 'Perfume Samples',
    description: 'Sample vials serve critical marketing functions—enabling fragrance discovery and driving full-size conversions. Presentation quality influences brand perception.',
    image: '/images/products/perfume-sample-gift-box.webp',
    imageAlt: 'perfume sample gift box',
    features: [
      'Glass vials with spray or dab application',
      'Plastic atomizers for cost-effective sampling',
      'Capacities: 1ml-5ml',
      'Sampling cards or packets for distribution',
    ],
    idealFor: 'Department store sampling, subscription boxes, promotional campaigns, discovery sets',
    link: '/all-applications/sample-perfume-bottles/',
  },
  {
    title: 'Essential Oil Bottles',
    description: 'Essential oil bottles provide protection for highly concentrated botanical extracts that require shielding from light, air, and temperature fluctuations.',
    image: '/images/products/green-essential-oil-bottle.webp',
    imageAlt: 'green essential oil bottle',
    features: [
      'Amber or cobalt glass provides 99%+ UV protection against light degradation',
      'Droppers deliver consistent drop size (0.05ml per drop)',
      'Chemical-resistant glass',
      'Capacities: 5ml-100ml',
    ],
    idealFor: 'Pure essential oils, fragrance oils, carrier oil blends, massage oil concentrates, natural perfume oils',
    link: '/all-applications/essential-oil-bottles/',
  },
]

export const personalCareProducts: ProductCardProps[] = [
  {
    title: 'Shampoo & Conditioner Bottles',
    description: 'Hair care bottles face unique environmental challenges: moisture exposure, slippery handling, and frequent opening/closing. Design must balance moisture resistance with easy one-handed operation.',
    image: '/images/products/plastic-containers-for-shampoo.jpg.webp',
    imageAlt: 'plastic containers for shampoo',
    features: [
      'Dispensing options: regular pump, airless pump, flip-top cap, disc-top, custom',
      'Ergonomic shapes for wet-hand grip',
      'Capacities: 200ml-1000ml (standard: 250ml, 500ml, 750ml)',
    ],
    idealFor: 'Shampoos, conditioners, co-wash products, hair masks, scalp treatments',
    link: '/all-applications/shampoo-bottles/',
  },
  {
    title: 'Bath & Body',
    description: 'Body wash and lotion bottles require durable, moisture-resistant packaging with easy-dispensing mechanisms for whole-body application. Their non-slip designs for daily bathroom use.',
    image: '/images/products/HDPE-shampoo-bottle.webp',
    imageAlt: 'HDPE shampoo bottle',
    features: [
      'Dispensing options: regular pump, airless pump, flip-top cap, disc-top, custom',
      'Capacities: 250ml-1000ml (common sizes: 400ml, 500ml, 750ml)',
      'Material options: HDPE for durability, PET for clarity, PCR plastics for sustainability',
    ],
    idealFor: 'Body washes, shower gels, body lotions, body milks, bubble bath, moisturizing creams, in-shower body conditioners',
    link: '/all-applications/body-lotion-bottles/',
  },
  {
    title: 'Body Butter Jars',
    description: 'Body butter jars feature wide-mouth openings designed for thick, luxurious formulations that require easy scooping access. ',
    image: '/images/products/250g-body-scrub-jar.webp',
    imageAlt: '250g body scrub jar',
    features: [
      'Wide-mouth designs (50mm-80mm diameter) for finger or spatula application',
      'Thick-walled construction maintains product temperature stability',
      'Capacities: 100ml-500ml (common sizes: 200ml, 250ml, 300ml)',
      'Screw caps or snap-on lids ensure secure closure',
    ],
    idealFor: 'Whipped body butters, rich body balms, intensive moisturizers, massage butters, overnight body masks',
    link: '/all-applications/body-butter-jars/',
  },
  {
    title: 'Foam Pump Bottles',
    description: 'Foam pump technology transforms liquid formulations into rich lather, enhancing user experience while reducing product consumption per use (25-30% product savings).',
    image: '/images/products/foam-pump-bottles.webp',
    imageAlt: 'foam pump bottles',
    features: [
      'Foaming pump mechanisms create rich, airy lather',
      'Special formulation requirements (diluted surfactant solutions)',
      'Capacities: 100ml-500ml',
      'Refillable designs for sustainability',
    ],
    idealFor: 'Foaming hand soaps, foam cleansers, mousse-textured products, styling mousses, shaving foams',
    link: '/all-applications/foam-pump-bottles/',
  },
]
