import { ProductCardProps } from './ProductCard'

export const skincareProducts: ProductCardProps[] = [
  {
    titleKey: 'allApplications.products.faceCreamJars.title',
    descriptionKey: 'allApplications.products.faceCreamJars.description',
    image: '/images/products/frosting-face-cream-jar.webp',
    imageAltKey: 'allApplications.products.faceCreamJars.imageAlt',
    featuresKeys: [
      'allApplications.products.faceCreamJars.features.0',
      'allApplications.products.faceCreamJars.features.1',
      'allApplications.products.faceCreamJars.features.2',
      'allApplications.products.faceCreamJars.features.3',
    ],
    idealForKey: 'allApplications.products.faceCreamJars.idealFor',
    link: '/all-applications/face-cream-jars/',
  },
  {
    titleKey: 'allApplications.products.faceLotionBottles.title',
    descriptionKey: 'allApplications.products.faceLotionBottles.description',
    image: '/images/products/Wholesale-HDPE-lotion-pump-bottles.webp',
    imageAltKey: 'allApplications.products.faceLotionBottles.imageAlt',
    featuresKeys: [
      'allApplications.products.faceLotionBottles.features.0',
      'allApplications.products.faceLotionBottles.features.1',
      'allApplications.products.faceLotionBottles.features.2',
      'allApplications.products.faceLotionBottles.features.3',
    ],
    idealForKey: 'allApplications.products.faceLotionBottles.idealFor',
    link: '/all-applications/lotion-bottles/',
  },
  {
    titleKey: 'allApplications.products.serumBottles.title',
    descriptionKey: 'allApplications.products.serumBottles.description',
    image: '/images/products/glass-serum-bottles.jpg.webp',
    imageAltKey: 'allApplications.products.serumBottles.imageAlt',
    featuresKeys: [
      'allApplications.products.serumBottles.features.0',
      'allApplications.products.serumBottles.features.1',
      'allApplications.products.serumBottles.features.2',
      'allApplications.products.serumBottles.features.3',
    ],
    idealForKey: 'allApplications.products.serumBottles.idealFor',
    link: '/all-applications/serum-bottles/',
  },
  {
    titleKey: 'allApplications.products.glassVials.title',
    descriptionKey: 'allApplications.products.glassVials.description',
    image: '/images/products/serum-vial.webp',
    imageAltKey: 'allApplications.products.glassVials.imageAlt',
    featuresKeys: [
      'allApplications.products.glassVials.features.0',
      'allApplications.products.glassVials.features.1',
      'allApplications.products.glassVials.features.2',
      'allApplications.products.glassVials.features.3',
    ],
    idealForKey: 'allApplications.products.glassVials.idealFor',
    link: '/all-applications/glass-vials/',
  },
]

export const skincareProducts2: ProductCardProps[] = [
  {
    titleKey: 'allApplications.products.rollOnBottles.title',
    descriptionKey: 'allApplications.products.rollOnBottles.description',
    image: '/images/products/roll-on-bottle-for-eye-serum.webp',
    imageAltKey: 'allApplications.products.rollOnBottles.imageAlt',
    featuresKeys: [
      'allApplications.products.rollOnBottles.features.0',
      'allApplications.products.rollOnBottles.features.1',
      'allApplications.products.rollOnBottles.features.2',
      'allApplications.products.rollOnBottles.features.3',
    ],
    idealForKey: 'allApplications.products.rollOnBottles.idealFor',
    link: '/all-applications/roll-on-bottles/',
  },
  {
    titleKey: 'allApplications.products.sprayBottles.title',
    descriptionKey: 'allApplications.products.sprayBottles.description',
    image: '/images/products/spray-bottle-design.webp',
    imageAltKey: 'allApplications.products.sprayBottles.imageAlt',
    featuresKeys: [
      'allApplications.products.sprayBottles.features.0',
      'allApplications.products.sprayBottles.features.1',
      'allApplications.products.sprayBottles.features.2',
      'allApplications.products.sprayBottles.features.3',
    ],
    idealForKey: 'allApplications.products.sprayBottles.idealFor',
    link: '/all-applications/spray-bottles/',
  },
  {
    titleKey: 'allApplications.products.tonerBottles.title',
    descriptionKey: 'allApplications.products.tonerBottles.description',
    image: '/images/products/skincare-bottle-packaging-for-hydrating-toner.webp',
    imageAltKey: 'allApplications.products.tonerBottles.imageAlt',
    featuresKeys: [
      'allApplications.products.tonerBottles.features.0',
      'allApplications.products.tonerBottles.features.1',
      'allApplications.products.tonerBottles.features.2',
      'allApplications.products.tonerBottles.features.3',
    ],
    idealForKey: 'allApplications.products.tonerBottles.idealFor',
    link: '/all-applications/toner-bottles/',
  },
  {
    titleKey: 'allApplications.products.sunscreenPackaging.title',
    descriptionKey: 'allApplications.products.sunscreenPackaging.description',
    image: '/images/products/squeezable-cosmetic-tube-sunscreen-bottle.webp',
    imageAltKey: 'allApplications.products.sunscreenPackaging.imageAlt',
    featuresKeys: [
      'allApplications.products.sunscreenPackaging.features.0',
      'allApplications.products.sunscreenPackaging.features.1',
      'allApplications.products.sunscreenPackaging.features.2',
      'allApplications.products.sunscreenPackaging.features.3',
    ],
    idealForKey: 'allApplications.products.sunscreenPackaging.idealFor',
    link: '/all-applications/sunscreen-packaging/',
  },
]

export const makeupProducts: ProductCardProps[] = [
  {
    titleKey: 'allApplications.products.foundationBottles.title',
    descriptionKey: 'allApplications.products.foundationBottles.description',
    image: '/images/products/new-design-foundation-bottles.webp',
    imageAltKey: 'allApplications.products.foundationBottles.imageAlt',
    featuresKeys: [
      'allApplications.products.foundationBottles.features.0',
      'allApplications.products.foundationBottles.features.1',
      'allApplications.products.foundationBottles.features.2',
      'allApplications.products.foundationBottles.features.3',
    ],
    idealForKey: 'allApplications.products.foundationBottles.idealFor',
    link: '/all-applications/foundation-bottles/',
  },
  {
    titleKey: 'allApplications.products.lipGlossTubes.title',
    descriptionKey: 'allApplications.products.lipGlossTubes.description',
    image: '/images/products/Eco-friendly-lip-gloss-tube.webp',
    imageAltKey: 'allApplications.products.lipGlossTubes.imageAlt',
    featuresKeys: [
      'allApplications.products.lipGlossTubes.features.0',
      'allApplications.products.lipGlossTubes.features.1',
      'allApplications.products.lipGlossTubes.features.2',
      'allApplications.products.lipGlossTubes.features.3',
    ],
    idealForKey: 'allApplications.products.lipGlossTubes.idealFor',
    link: '/all-applications/lip-gloss-tubes/',
  },
  {
    titleKey: 'allApplications.products.mascaraTubes.title',
    descriptionKey: 'allApplications.products.mascaraTubes.description',
    image: '/images/products/metallic-lip-gloss-tube.webp',
    imageAltKey: 'allApplications.products.mascaraTubes.imageAlt',
    featuresKeys: [
      'allApplications.products.mascaraTubes.features.0',
      'allApplications.products.mascaraTubes.features.1',
      'allApplications.products.mascaraTubes.features.2',
      'allApplications.products.mascaraTubes.features.3',
    ],
    idealForKey: 'allApplications.products.mascaraTubes.idealFor',
    link: '/all-applications/mascara-tube/',
  },
  {
    titleKey: 'allApplications.products.makeupRemovers.title',
    descriptionKey: 'allApplications.products.makeupRemovers.description',
    image: '/images/products/airless-jar.webp',
    imageAltKey: 'allApplications.products.makeupRemovers.imageAlt',
    featuresKeys: [
      'allApplications.products.makeupRemovers.features.0',
      'allApplications.products.makeupRemovers.features.1',
      'allApplications.products.makeupRemovers.features.2',
      'allApplications.products.makeupRemovers.features.3',
    ],
    idealForKey: 'allApplications.products.makeupRemovers.idealFor',
    link: '/all-applications/makeup-remover-bottles/',
  },
]

export const fragranceProducts: ProductCardProps[] = [
  {
    titleKey: 'allApplications.products.perfumeBottles.title',
    descriptionKey: 'allApplications.products.perfumeBottles.description',
    image: '/images/products/perfume-bottle-new-design.webp',
    imageAltKey: 'allApplications.products.perfumeBottles.imageAlt',
    featuresKeys: [
      'allApplications.products.perfumeBottles.features.0',
      'allApplications.products.perfumeBottles.features.1',
      'allApplications.products.perfumeBottles.features.2',
      'allApplications.products.perfumeBottles.features.3',
    ],
    idealForKey: 'allApplications.products.perfumeBottles.idealFor',
    link: '/all-applications/perfume-bottles/',
  },
  {
    titleKey: 'allApplications.products.portableBottles.title',
    descriptionKey: 'allApplications.products.portableBottles.description',
    image: '/images/products/portable-perfume-bottle.webp',
    imageAltKey: 'allApplications.products.portableBottles.imageAlt',
    featuresKeys: [
      'allApplications.products.portableBottles.features.0',
      'allApplications.products.portableBottles.features.1',
      'allApplications.products.portableBottles.features.2',
      'allApplications.products.portableBottles.features.3',
    ],
    idealForKey: 'allApplications.products.portableBottles.idealFor',
    link: '/all-applications/portable-perfume-bottles/',
  },
  {
    titleKey: 'allApplications.products.perfumeSamples.title',
    descriptionKey: 'allApplications.products.perfumeSamples.description',
    image: '/images/products/perfume-sample-gift-box.webp',
    imageAltKey: 'allApplications.products.perfumeSamples.imageAlt',
    featuresKeys: [
      'allApplications.products.perfumeSamples.features.0',
      'allApplications.products.perfumeSamples.features.1',
      'allApplications.products.perfumeSamples.features.2',
      'allApplications.products.perfumeSamples.features.3',
    ],
    idealForKey: 'allApplications.products.perfumeSamples.idealFor',
    link: '/all-applications/sample-perfume-bottles/',
  },
  {
    titleKey: 'allApplications.products.essentialOilBottles.title',
    descriptionKey: 'allApplications.products.essentialOilBottles.description',
    image: '/images/products/green-essential-oil-bottle.webp',
    imageAltKey: 'allApplications.products.essentialOilBottles.imageAlt',
    featuresKeys: [
      'allApplications.products.essentialOilBottles.features.0',
      'allApplications.products.essentialOilBottles.features.1',
      'allApplications.products.essentialOilBottles.features.2',
      'allApplications.products.essentialOilBottles.features.3',
    ],
    idealForKey: 'allApplications.products.essentialOilBottles.idealFor',
    link: '/all-applications/essential-oil-bottles/',
  },
]

export const personalCareProducts: ProductCardProps[] = [
  {
    titleKey: 'allApplications.products.shampooConditionerBottles.title',
    descriptionKey: 'allApplications.products.shampooConditionerBottles.description',
    image: '/images/products/plastic-containers-for-shampoo.jpg.webp',
    imageAltKey: 'allApplications.products.shampooConditionerBottles.imageAlt',
    featuresKeys: [
      'allApplications.products.shampooConditionerBottles.features.0',
      'allApplications.products.shampooConditionerBottles.features.1',
      'allApplications.products.shampooConditionerBottles.features.2',
    ],
    idealForKey: 'allApplications.products.shampooConditionerBottles.idealFor',
    link: '/all-applications/shampoo-bottles/',
  },
  {
    titleKey: 'allApplications.products.bathBody.title',
    descriptionKey: 'allApplications.products.bathBody.description',
    image: '/images/products/HDPE-shampoo-bottle.webp',
    imageAltKey: 'allApplications.products.bathBody.imageAlt',
    featuresKeys: [
      'allApplications.products.bathBody.features.0',
      'allApplications.products.bathBody.features.1',
      'allApplications.products.bathBody.features.2',
    ],
    idealForKey: 'allApplications.products.bathBody.idealFor',
    link: '/all-applications/body-lotion-bottles/',
  },
  {
    titleKey: 'allApplications.products.bodyButterJars.title',
    descriptionKey: 'allApplications.products.bodyButterJars.description',
    image: '/images/products/250g-body-scrub-jar.webp',
    imageAltKey: 'allApplications.products.bodyButterJars.imageAlt',
    featuresKeys: [
      'allApplications.products.bodyButterJars.features.0',
      'allApplications.products.bodyButterJars.features.1',
      'allApplications.products.bodyButterJars.features.2',
      'allApplications.products.bodyButterJars.features.3',
    ],
    idealForKey: 'allApplications.products.bodyButterJars.idealFor',
    link: '/all-applications/body-butter-jars/',
  },
  {
    titleKey: 'allApplications.products.foamPumpBottles.title',
    descriptionKey: 'allApplications.products.foamPumpBottles.description',
    image: '/images/products/foam-pump-bottles.webp',
    imageAltKey: 'allApplications.products.foamPumpBottles.imageAlt',
    featuresKeys: [
      'allApplications.products.foamPumpBottles.features.0',
      'allApplications.products.foamPumpBottles.features.1',
      'allApplications.products.foamPumpBottles.features.2',
      'allApplications.products.foamPumpBottles.features.3',
    ],
    idealForKey: 'allApplications.products.foamPumpBottles.idealFor',
    link: '/all-applications/foam-pump-bottles/',
  },
]
